### ISSUE TITLE
Re-enable Rubocop

### ISSUE THREAD

**Issue by abinoam** [Ptico/inflecto#15]
I saw this on `.rubocop.yml`

```yaml
AllCops:
  Exclude:
    - 'lib/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'flexus.gemspec'
    - 'vendor/**/*'
```

This `- 'lib/**/*'` just makes rubocop useless!

I have been using [pronto](https://github.com/prontolabs/pronto) to help fixing these stylistic thing step by step instead of everything in a row.

Opening this issue to remember fixing this.
